################################################################################
#
# linux-backports
#
################################################################################

ifeq ($(BR2_PACKAGE_BACKPORT_MAC80211_6_1_X),y)
BACKPORT_MAC80211_VERSION_MAJOR = 6.1.110
BACKPORT_MAC80211_MINIMAL_KVER_MAJOR = 4
BACKPORT_MAC80211_MINIMAL_KVER_MINOR = 11
else ifeq ($(BR2_PACKAGE_BACKPORT_MAC80211_5_10_X),y)
BACKPORT_MAC80211_VERSION_MAJOR = 5.10.110
BACKPORT_MAC80211_MINIMAL_KVER_MAJOR = 3
BACKPORT_MAC80211_MINIMAL_KVER_MINOR = 10
else
# use default the latest version as default
BACKPORT_MAC80211_VERSION_MAJOR = 5.15.58
BACKPORT_MAC80211_MINIMAL_KVER_MAJOR = 4
BACKPORT_MAC80211_MINIMAL_KVER_MINOR = 4
endif

BACKPORT_MAC80211_VERSION = $(BACKPORT_MAC80211_VERSION_MAJOR)-1
BACKPORT_MAC80211_SOURCE = backports-$(BACKPORT_MAC80211_VERSION).tar.xz
BACKPORT_MAC80211_SITE = $(BR2_KERNEL_MIRROR)/linux/kernel/projects/backports/stable/v$(BACKPORT_MAC80211_VERSION_MAJOR)
BACKPORT_MAC80211_LICENSE = GPL-2.0
BACKPORT_MAC80211_LICENSE_FILES = \
	COPYING \
	LICENSES/exceptions/Linux-syscall-note \
	LICENSES/preferred/GPL-2.0

# flex and bison are needed to generate kconfig parser. We use the
# same logic as the linux kernel (we add host dependencies only if
# host does not have them). See linux/linux.mk and
# support/dependencies/check-host-bison-flex.mk.
BACKPORT_MAC80211_DEPENDENCIES = \
	$(BR2_BISON_HOST_DEPENDENCY) \
	$(BR2_FLEX_HOST_DEPENDENCY)

ifeq ($(BR2_PACKAGE_BACKPORT_MAC80211_USE_DEFCONFIG),y)
BACKPORT_MAC80211_KCONFIG_FILE = $(BACKPORT_MAC80211_DIR)/defconfigs/$(call qstrip,$(BR2_PACKAGE_BACKPORT_MAC80211_DEFCONFIG))
else ifeq ($(BR2_PACKAGE_BACKPORT_MAC80211_USE_CUSTOM_CONFIG),y)
BACKPORT_MAC80211_KCONFIG_FILE = $(call qstrip,$(BR2_PACKAGE_BACKPORT_MAC80211_CUSTOM_CONFIG_FILE))
endif

BACKPORT_MAC80211_KCONFIG_FRAGMENT_FILES = $(call qstrip,$(BR2_PACKAGE_BACKPORT_MAC80211_CONFIG_FRAGMENT_FILES))
BACKPORT_MAC80211_KCONFIG_OPTS = $(BACKPORT_MAC80211_MAKE_OPTS)

# linux-backports' build system expects the config options to be present
# in the environment, and it is so when using their custom buildsystem,
# because they are set in the main Makefile, which then calls a second
# Makefile.
#
# In our case, we do not use that first Makefile. So, we parse the
# .config file, filter-out comment lines and put the rest as command
# line variables.
#
# BACKPORT_MAC80211_MAKE_OPTS is used by the kconfig-package infra, while
# BACKPORT_MAC80211_MODULE_MAKE_OPTS is used by the kernel-module infra.
#
BACKPORT_MAC80211_MAKE_OPTS = \
	LEX=flex \
	YACC=bison \
	BACKPORT_DIR=$(@D) \
	KLIB_BUILD=$(LINUX_DIR) \
	KLIB=$(TARGET_DIR)/lib/modules/$(LINUX_VERSION_PROBED) \
	INSTALL_MOD_DIR=backports \
	MAKEFILES=$(@D)/.config

BACKPORT_MAC80211_MODULE_MAKE_OPTS = $(BACKPORT_MAC80211_MAKE_OPTS)

# This file is not automatically generated by 'oldconfig' that we use in
# the kconfig-package infrastructure. In the linux buildsystem, it is
# generated by running silentoldconfig, but that's not the case for
# linux-backports: it uses a hand-crafted rule to generate that file.
define BACKPORT_MAC80211_KCONFIG_FIXUP_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D) $(BACKPORT_MAC80211_MAKE_OPTS) backport-include/backport/autoconf.h
endef

# Checks to give errors that the user can understand
ifeq ($(BR_BUILDING),y)

ifeq ($(BR2_PACKAGE_BACKPORT_MAC80211_USE_DEFCONFIG),y)
ifeq ($(call qstrip,$(BR2_PACKAGE_BACKPORT_MAC80211_DEFCONFIG)),)
$(error No linux-backports defconfig name specified, check your BR2_PACKAGE_BACKPORT_MAC80211_DEFCONFIG setting)
endif
endif

ifeq ($(BR2_PACKAGE_BACKPORT_MAC80211_USE_CUSTOM_CONFIG),y)
ifeq ($(call qstrip,$(BR2_PACKAGE_BACKPORT_MAC80211_CUSTOM_CONFIG_FILE)),)
$(error No linux-backports configuration file specified, check your BR2_PACKAGE_BACKPORT_MAC80211_CUSTOM_CONFIG_FILE setting)
endif
endif

endif # BR_BUILDING

$(eval $(kernel-module))
$(eval $(kconfig-package))

# linux-backports' own .config file needs options from the kernel's own
# .config file. The dependencies handling in the infrastructure does not
# allow to express this kind of dependencies. Besides, linux.mk might
# not have been parsed yet, so the Linux build dir LINUX_DIR is not yet
# known. Thus, we use a "secondary expansion" so the rule is re-evaluated
# after all Makefiles are parsed, and thus at that time we will have the
# LINUX_DIR variable set to the proper value. Moreover, since linux-4.19,
# the kernel's build system internally touches its .config file, so we
# can't use it as a stamp file. We use the LINUX_KCONFIG_STAMP_DOTCONFIG
# instead.
#
# Furthermore, we want to check the kernel version is compatible with
# linux-backports. To avoid overriding linux-backports'
# KCONFIG_STAMP_DOTCONFIG rule defined in the kconfig-package infra, we
# use an intermediate stamp-file.
#
# Finally, it must also come after the call to kconfig-package, so we get
# BACKPORT_MAC80211_DIR properly defined (because the target part of the
# rule is not re-evaluated).
#
$(BACKPORT_MAC80211_DIR)/$(BACKPORT_MAC80211_KCONFIG_STAMP_DOTCONFIG): $(BACKPORT_MAC80211_DIR)/.stamp_check_kernel_version

.SECONDEXPANSION:
$(BACKPORT_MAC80211_DIR)/.stamp_check_kernel_version: $$(LINUX_DIR)/$$(LINUX_KCONFIG_STAMP_DOTCONFIG)
	$(Q)KVER=$(LINUX_VERSION_PROBED); \
	MIN_KVER_MAJOR=$(BACKPORT_MAC80211_MINIMAL_KVER_MAJOR); \
	MIN_KVER_MINOR=$(BACKPORT_MAC80211_MINIMAL_KVER_MINOR); \
	KVER_MAJOR=`echo $${KVER} | sed 's/^\([0-9]*\)\..*/\1/'`; \
	KVER_MINOR=`echo $${KVER} | sed 's/^[0-9]*\.\([0-9]*\).*/\1/'`; \
	if [ $${KVER_MAJOR} -lt $(BACKPORT_MAC80211_MINIMAL_KVER_MAJOR) \
		-o \( $${KVER_MAJOR} -eq $(BACKPORT_MAC80211_MINIMAL_KVER_MAJOR) \
			-a $${KVER_MINOR} -lt $(BACKPORT_MAC80211_MINIMAL_KVER_MINOR) \
		\) ]; then \
		printf "Linux version '%s' is too old for linux-backports (needs %s.%s or later)\n" \
			"$${KVER}" \
			"$(BACKPORT_MAC80211_MINIMAL_KVER_MAJOR)" \
			"$(BACKPORT_MAC80211_MINIMAL_KVER_MINOR)"; \
		exit 1; \
	fi
	$(Q)touch $(@)
