# SPDX-License-Identifier: ISC
#
# Makefile fragment for Broadcom 802.11 Networking Device Driver
#
# Copyright (c) 2010 Broadcom Corporation
#

# common flags
subdir-ccflags-$(CONFIG_BACKPORT_BRCMDBG)	+= -DDEBUG

obj-$(CONFIG_BACKPORT_BRCMUTIL)	+= brcmutil/
obj-$(CONFIG_BACKPORT_BRCMFMAC)	+= brcmfmac/
obj-$(CONFIG_BACKPORT_BRCMSMAC)	+= brcmsmac/
