obj-$(CONFIG_BACKPORT_MHI_BUS) += mhi.o
mhi-y := init.o main.o pm.o boot.o
mhi-$(CONFIG_BACKPORT_MHI_BUS_DEBUG) += debugfs.o

obj-$(CONFIG_BACKPORT_MHI_BUS_PCI_GENERIC) += mhi_pci_generic.o
mhi_pci_generic-y += pci_generic.o
