# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_BACKPORT_IPW2100) += ipw2x00/
obj-$(CONFIG_BACKPORT_IPW2200) += ipw2x00/

obj-$(CONFIG_BACKPORT_IWLEGACY)	+= iwlegacy/

obj-$(CONFIG_BACKPORT_IWLWIFI)	+= iwlwifi/
